### ISSUE TITLE
Out of data error on Windows with 2 CUDA capable cards

### ISSUE THREAD

**Issue by TheDailySpank** [minimaxir/aitextgen#116]
Long story short, Torch doesn't like working with multiple GPUs on Windows (shared storage related issue).

Fix is to set n_gpu = 1 in train()

Any chance we could set n_gpu=1 as a default when running on Windows?

```
import os
if os.name == 'nt':
    n_gpu = 1
```

**Comment by minimaxir** [comment]
Sure, can do something like that. (w/ an appropriate log message)

**Comment by TheDailySpank** [comment]
Awesome. Thank you!

I had almost stopped trying to get it to work after about 3 days of tracking down the cause.
