### ISSUE TITLE
Trained model size and speed issues

### ISSUE THREAD

**Issue by jakobgreenfeld** [minimaxir/aitextgen#117]
When I'm fine-tuning the smallest GPT2 model on my computer, the `pytorch_model.bin` file that's saved in the trained_model folder is just 3.6 MB large. And more importantly, when I'm loading it and generate text with it, it usually takes less than a second. 

But when I'm executing the same code on Google Colab, the  `pytorch_model.bin` file is 500 MB large and extremely slow when it comes to generating text. Is there any option I can use to make sure it's generating the smaller version of the `pytorch_model.bin` file? Or what of course would be equally good, if there is an option that allows me to accelerate the text generation process.

This is the code I'm using:

```
from aitextgen.TokenDataset import TokenDataset
from aitextgen.tokenizers import train_tokenizer
from aitextgen.utils import GPT2ConfigCPU
from aitextgen import aitextgen

# The name of the input text for training
file_name = "input.txt"

# Train a custom BPE Tokenizer on the downloaded text
# This will save one file: `aitextgen.tokenizer.json`, which contains the
# information needed to rebuild the tokenizer.
train_tokenizer(file_name)
tokenizer_file = "aitextgen.tokenizer.json"

# GPT2ConfigCPU is a mini variant of GPT-2 optimized for CPU-training
# e.g. the # of input tokens here is 64 vs. 1024 for base GPT-2.
config = GPT2ConfigCPU()

# Instantiate aitextgen using the created tokenizer and config
ai = aitextgen(tf_gpt2="124M",tokenizer_file=tokenizer_file, config=config)

# You can build datasets for training by creating TokenDatasets,
# which automatically processes the dataset with the appropriate size.
data = TokenDataset(file_name, tokenizer_file=tokenizer_file, block_size=64)

# Train the model! It will save pytorch_model.bin periodically and after completion.
# On a 2020 8-core iMac, this took ~25 minutes to run.
ai.train(data, batch_size=8, num_steps=1000, generate_every=500, save_every=500)

# Generate text from it!
ai.generate()
```

**Comment by jakobgreenfeld** [comment]
I just discovered that when I change

`ai = aitextgen(tf_gpt2="124M",tokenizer_file=tokenizer_file, config=config)`

to 

`ai = aitextgen(tokenizer_file=tokenizer_file, config=config)`

the generated `pytorch_model.bin` file is always super small and loads extremely fast. Not sure why it happens so I'd appreciate any comments! Is there any way to accelerate larger GPT2 models in a similar way?

**Comment by jakobgreenfeld** [comment]
Figured it out I think. When you don't specify a GPT version, it's actually not fine-tuning but training a completely new model from scratch.

**Comment by minimaxir** [comment]
Correct.

The 500MB model is the size of the pretrained GPT-2 as released from OpenAI in 2019. Training/generation assumes that you're using a GPU as on Colab; obviously it will run much slower on a GPU.

The smaller models based off of `GPT2ConfigCPU()` are deliberately much smaller to demo the training on a local PC, and consequently the generation will be proportionally faster.

An ongoing goal of `aitextgen` is to improve CPU performance of larger models (e.g. ONNX conversion which would result in a 4x speedup on paper)!
