### ISSUE TITLE
Import only the generate function

### ISSUE THREAD

**Issue by lautaropacella** [minimaxir/aitextgen#125]
Hello! I made an app based on AiTextGen because I thought it was awesome and wanted to show how tweaking the parameters would change the result.

I already have the model trained and my tokens, but the problem is that to generate from it, I need to import the entire package which is really heavy, so the cloud service I was using (Heroku) won't allow me to deploy it (it caps the slug limit size).

Is it possible to import just the generation part of the package so it's a lighter version?
Regards!

**Comment by minimaxir** [comment]
Unfortunately no since everything is tightly coupled, however I have plans for a variant of aitextgen which is nicer dependency-wise for cloud deployment. (expecting a 0.7.0)
