### ISSUE TITLE
How can I train it by chatting with it? 

### ISSUE THREAD

**Issue by Hunter2807** [minimaxir/aitextgen#137]
Hey! 

I came to know about your module, and it's good. But I want to know if there is a way to **train** it by **chatting** with it.. It would be better (for people like me at least). I don't have any code because I can't understand from where to start 😦 

Thanks in advance

**Comment by galaxyentity904** [comment]
Unfortunately the models do not work like that from what I can tell- you have to pretrain it with text or put up with something like GPT-2 or GPT-NEO. You can't train it while generating- and the model does not exactly talk to you in a sense, more find something mentioned and piece it together, if that makes sense? This is from me who has trained 4 models and am using the GPT-NEO 1.3B model

**Comment by minimaxir** [comment]
@galaxyentity904 is essentially correct. You could manually finetune it on your conversations after talking with it, but that's the extent of it.

Language modeling doesn't work like reinforcement learning unfortunately.
