### ISSUE TITLE
Can't generate text while loading 124M locally

### ISSUE THREAD

**Issue by MK096** [minimaxir/aitextgen#139]
While loading 124M on my local machine, i get following error

_OSError: Couldn't reach server at 'models\124M\config.json' to download configuration file or configuration file is not a valid JSON file. Please check network or file content here: models\124M\config.json._
 
Note: I was able to run interactivesample that comes inbuild with gpt2 ,

**Code:**
   ai = aitextgen(model_folder="models//124M",tokenizer_file="tokenizer_config.json")
    ai.generate()
    ai.generate(n=3, max_length=100)
    ai.generate(n=3, prompt="I believe in unicorns because", max_length=100)

Here are files that are under my 124M model which i downloaded using download_model.py from gpt2. There is no file as config.json in this. ( iwas able to run the interactivesample though w/o using aitextgen)

![124M](https://user-images.githubusercontent.com/20142735/122030885-9a9c3500-cde7-11eb-981f-9ec7bd9777e1.PNG)

**Comment by minimaxir** [comment]
Those are TensorFlow files. You must [convert the checkpoint to PyTorch](https://docs.aitextgen.io/gpt-2-simple/) first.

**Comment by MK096** [comment]
> Those are TensorFlow files. You must [convert the checkpoint to PyTorch](https://docs.aitextgen.io/gpt-2-simple/) first.

Thanks for the reply.
I tried that but i get following error:
![error](https://user-images.githubusercontent.com/20142735/123535525-cc918d80-d73d-11eb-86b9-85a67f8096fc.PNG)

CMD : transformers-cli convert --model_type gpt2 --tf_checkpoint checkpoint/run1_netflix --pytorch_dump_output pytorch --config checkpoint/run1_netflix/hparams.json

My directory:
![directory](https://user-images.githubusercontent.com/20142735/123535531-dca96d00-d73d-11eb-9d40-b200e21ccf39.PNG)

**Comment by MK096** [comment]
> Those are TensorFlow files. You must [convert the checkpoint to PyTorch](https://docs.aitextgen.io/gpt-2-simple/) first.

Thanks for the reply.
It worked.
