### ISSUE TITLE
Finetuned model very slow

### ISSUE THREAD

**Issue by MK096** [minimaxir/aitextgen#143]
After finetuning 355M when i downloaded the checkpoint and ried to run it on local machine,

i am stuck at "Loading checkpoint C:\Users\......\model-1500"

Before finetuning the model used to run fast but now it won't even load

**Comment by minimaxir** [comment]
Were you able to run a 355M model on your local machine without finetuning?

A 355M model can be difficult for a consumer machine without a GPU.

**Comment by MK096** [comment]
> Were you able to run a 355M model on your local machine without finetuning?
> 
> A 355M model can be difficult for a consumer machine without a GPU.

Sorry for the late reply.
Yes, i was able to generate but i had to reduce nsample to 1 on my local machine.
