### ISSUE TITLE
Could you elaborate on why validation doesn't really help in finding overfitting? 

### ISSUE THREAD

**Issue by redthing1** [minimaxir/aitextgen#153]
I was curious about this in your features page:

> Validation is deliberately not implemented since it serves as more of a crutch and doesn't provide that much help in identifying overfitting

Could you explain a bit? I was under the impression that validation was a useful metric for training causal language models.

**Comment by minimaxir** [comment]
It's good for objective metrics (which is what the language modeling research papers use), but in the end for text generation, there's a lot of subjectivity (especially with temperatures) which a validation pass don't help as much to identify.
