### ISSUE TITLE
Directory Issue - MyDrive

### ISSUE THREAD

**Issue by Onat-T** [minimaxir/aitextgen#163]
Hi Max!

Thank you very much for your hard work. The Colab is so easy and fun to follow.

I'm really liking this new version, but I'm having a very similar issue with the one I had with the previous version. I simply can't run "copy_file_from_gdrive(file_name)". 

It prints out the error: "FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/My Drive/sonnet_train.txt".

I think there is a simple reason for this: There is no whitespace between MyDrive on my Google account. The folder name is always "MyDrive" and I can't change it.

Is anyone else having a similar problem? Any tips?

Thanks a lot!
Olly.

**Comment by leetfin** [comment]
PR #184 fixes this.
