### ISSUE TITLE
Cannot install aitextgen via pip3 - torch is missing.

### ISSUE THREAD

**Issue by IdeallyGrey** [minimaxir/aitextgen#168]
I'll preface this by saying I'm not sure if this error should be directed here or to pytorch.

When I try to install aitextgen via pip3 the process fails here:
```
Collecting torch>=1.6.0 (from aitextgen)
  Could not find a version that satisfies the requirement torch>=1.6.0 (from aitextgen) (from versions: )
No matching distribution found for torch>=1.6.0 (from aitextgen)
```
I've tried installing torch via `pip3 install torch`, but this replies with
 `Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting torch
  Could not find a version that satisfies the requirement torch (from versions: )
No matching distribution found for torch
`

I've tried using my laptop and my Raspberry Pi.
Installing any other package via pip3 works fine.

Again, not sure if this error should be directed here or to pytorch.

**Comment by IdeallyGrey** [comment]
Update: It seems that this error occurs with Python 3.10, but not with Python 3.8. This would lead me to believe that 3.10 is unsupported by PyTorch, but the PyTorch docs say that it should work with any version of Python above 3.5.

**Comment by D4n13l3k00** [comment]
You can get command for pytorch installation from https://pytorch.org
And u should use Python 3.6-3.9

**Comment by appvoid** [comment]
**Probably, what you want is this:**
If you are using Windows on CPU: 
`pip3 install torch torchvision torchaudio --user`
If you are using Windows on GPU:
`pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu113 --user`
