### ISSUE TITLE
How to load already trained models for more training or fine tuning?

### ISSUE THREAD

**Issue by Joybuke** [minimaxir/aitextgen#177]
Howdy there, I'm doing some training on a home computer and occasionally need to stop training/finetuning to use the computer. How exactly would I go about loading my model file (or a checkpoint if that's a feature) to continue training at a later time. Currently it doesn't seem this is possible and the model file is just overwritten when training starts again. .

**Comment by tientr** [comment]
Just load the model with parameter `model_folder` when init aitextgen. `ai = aitextgen(model_folder="./trained_model", to_gpu=True,fp16=True)`
