### ISSUE TITLE
Missing parameter `amp_backend=apex` with when using `fp16=True`

### ISSUE THREAD

**Issue by tientr** [minimaxir/aitextgen#180]
The error: `You have asked for amp_level='O1' but it's only supported with amp_backend='apex'.`

Pytorch lightning requires  `amp_backend=apex` in train params when calling `amp_level=01`. This can be fixed by adding code `train_params["amp_backend"] = "apex"` in train function of `aitextgen.py`.

**Comment by cuuupid** [comment]
+1, this makes it impossible to use `fp16` in any of the colab notebooks.

**Comment by leetfin** [comment]
+1
