### ISSUE TITLE
Generate to array of strings

### ISSUE THREAD

**Issue by HarshaLaxman** [minimaxir/aitextgen#19]
It seems the only options are to generate to stdout or a file. I want the result as an array of strings so I do this as a workaround:

```
ai = aitextgen()
ai.generate_to_file(n=10)

with open('generated_file.txt', 'r') as file:
    data = file.read().replace('\n', '')

data_arr = data.split("====================")[0:-1]
```

**Comment by minimaxir** [comment]
You can generate a list of strings by setting `return_as_list=True` to `generate()`, e.g.

```python
ai.generate(10, return_as_list=True)
```

Then you can do whatever you want with them.

**Comment by HarshaLaxman** [comment]
Awesome! Thanks :)
