### ISSUE TITLE
Is there a way to continue training on an existing model?

### ISSUE THREAD

**Issue by fen0s** [minimaxir/aitextgen#20]
Like, after 2000 steps I've got a trained model, and I wanna continue training it. In gpt2_simple, it was automatical and only asked you for run name. Is it even implemented yet? Couldn't find anything about that in neither docs nor source code.

**Comment by minimaxir** [comment]
You just need to reload the trained model, e.g.

```python
ai = aitextgen(model="pytorch_model.bin")
```

Then you can train on that further. (it is effectively the same as how gpt-2-simple handled it)

I'll add a note in the docs.

**Comment by fen0s** [comment]
Yeah, that's fine now.

**Comment by DrSnowbird** [comment]
With the new version, this what I did for 'continuous training model' - I debug into the code to find out the details to work as below:

model_folder = "./trained_model"
ai = aitextgen(model_folder=model_folder, to_gpu=True)
