### ISSUE TITLE
KeyError: 'biogpt'

### ISSUE THREAD

**Issue by breadbrowser** [minimaxir/aitextgen#210]
why can't I fine-tune biogpt?

**Comment by LuciferianInk** [comment]
Not all models are created equal. AITextGen was designed to support GPT-2 and GPT-Neo. If you want to use others, you'll have to update the code accordingly.

**Comment by breadbrowser** [comment]
> Not all models are created equal. AITextGen was designed to support GPT-2 and GPT-Neo. If you want to use others, you'll have to update the code accordingly.

![image](https://user-images.githubusercontent.com/64813014/229310739-00fb2806-9f98-436c-9647-d234d012e4e9.png)
