### ISSUE TITLE
[Colab exclusive] Colab freezes whole PC if getting back to notebook after disconnect

### ISSUE THREAD

**Issue by fen0s** [minimaxir/aitextgen#24]
Basically, what happens, is that Colab shows you the whole training from the start of code execution after reconnecting to the runtime, and during that proccess it just hangs up your PC. I guess, because too many cmd refreshing operations? Can't even move the cursor in that moment, so I have to hard reset my PC.

**Comment by minimaxir** [comment]
Colab is weird: I think there are some JS memory leaks, but that's not aitextgen specific per se. It works better in Safari than Chrome.

The only thing I think would cause it is the constant updates of the progress bar. It might be better to add an option to specify update intervals.

**Comment by fen0s** [comment]
Yeah, it's probably about constant updates. In my case, it started showing iterations from single, and after a few hundred, my PC just freezedm couldn't do anything but pull the plug.

**Comment by minimaxir** [comment]
I'll add the update rate as a configuration parameter, w/ 10 as the default.

**Comment by minimaxir** [comment]
v0.2.0 is released: see if that helps!

**Comment by fen0s** [comment]
Seems to be fine now.
