### ISSUE TITLE
__init__() got an unexpected keyword argument 'disable_validation'

### ISSUE THREAD

**Issue by lyan62** [minimaxir/aitextgen#33]
when I'm running the colab finetune example I'm getting this error.
which trace back to:    
trainer = pl.Trainer(**train_params)

**Comment by hnarayanan** [comment]
I'd like to second this error. It was working until a few days ago.

**Comment by hnarayanan** [comment]
Here is the stack trace:

```
100%
68570/68570 [00:02<00:00, 32633.39it/s]
06/20/2020 17:25:22 — INFO — aitextgen.TokenDataset — Encoding 68,570 sets of tokens from archive.txt.

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-8-57ab1a63b36a> in <module>()
      6          save_gdrive=True,
      7          learning_rate=1e-4,
----> 8          batch_size=1,
      9          )

/usr/local/lib/python3.6/dist-packages/aitextgen/aitextgen.py in train(self, train_data, output_dir, fp16, fp16_opt_level, n_gpu, n_tpu_cores, max_grad_norm, gradient_accumulation_steps, seed, learning_rate, weight_decay, adam_epsilon, warmup_steps, num_steps, save_every, generate_every, n_generate, loggers, batch_size, num_workers, benchmark, avg_loss_smoothing, save_gdrive, run_id, progress_bar_refresh_rate, **kwargs)
    563             train_params["distributed_backend"] = "ddp"
    564 
--> 565         trainer = pl.Trainer(**train_params)
    566         trainer.fit(train_model)
    567 

TypeError: __init__() got an unexpected keyword argument 'disable_validation'
```

**Comment by Kulinark** [comment]
This is due to pytorch-lightning incompatibility.
After installing the libraries, add the block:

!pip3 uninstall pytorch-lightning
!pip3 install pytorch-lightning==0.7.6

and confirm deletion
I apologize for bad English, I write through a translator

**Comment by hnarayanan** [comment]
Thank you! I was just about to say something similar after researching where the error was.

**Comment by hnarayanan** [comment]
Because there is a problem with unloading and reloading modules (which needs you to reset the kernel), it is easier if you just `!pip3 install pytorch-lightning==0.7.6` before `!pip install -q aitextgen`.

**Comment by minimaxir** [comment]
Yes, I haven't tested on `0.8.0` and it's relatively new. I'll add the lines as noted to the notebook for the time being.

**Comment by minimaxir** [comment]
So it turns out `disable_validation` was depreciated in `0.8.0` of `pytorch-lightning`, which makes sense.

I pushed out `0.2.1` of aitextgen removing that parameter and everything works fine. Closing.
