### ISSUE TITLE
Slow generation on GPU with 100% CPU used

### ISSUE THREAD

**Issue by chekalsky** [minimaxir/aitextgen#34]
Hi!

I've trained my own model (about 29M parameters) and trying to run generation with it on AWS EC2 instances.
I've tried to run a generator both on g4dn.large and p3.2xlarge instances (they have Tesla T4 and V100 respectievely). Here is the code:

```
ai = aitextgen(
    model=model_dir+'pytorch_model.bin', 
    vocab_file=model_dir+'aitextgen-vocab.json', 
    merges_file=model_dir+'aitextgen-merges.txt', 
    config=model_dir+'config.json',
    to_gpu=True
)

ai.generate(n=5, return_as_list=True, max_length=random.randint(80, 140), temperature=0.7, repetition_penalty=1.2)
```

Unfortunately, it takes about 3-5 seconds to generate it on Tesla T4 and on Tesla V100. And one of the CPU cores is going up to 100% at this time. GPU has about 1,5Gb GPU RAM taken and max. 25% of GPU processor usage on T4 and about 5% on V100.

So it looks like CPU is the bottleneck.
1. Is that OK, that CPU is so utilized during the generation process?
2. Is it possible to generate only using CPU?
3. Is it possible to run parallel execution on multiple cores?

Thank you!

**Comment by minimaxir** [comment]
Correct, it should not be using the CPU. And the `to_gpu` param is correctly used; if the host system did not have CUDA access, it would throw an assert.

Did you install CUDA a specific way on the EC2 instance?

**Comment by chekalsky** [comment]
I am using [this AMI](https://aws.amazon.com/marketplace/pp/B07S5FG49X?qid=1592659531222&ref_=srh_res_product_title&sr=0-4&stl=true). It has everything preinstalled, although I can't find `nvcc`, don't know, maybe it's important.

CUDA Version: 10.2
Driver Version: 440.64.00

<img width="647" alt="Screenshot 2020-06-20 at 22 12 56" src="https://user-images.githubusercontent.com/241584/85210806-5fd1ff00-b343-11ea-952e-992e89d1a846.png">

So it's 1.3 seconds per one generation on GPU and 1.8 seconds locally on 2,2 GHz 6-Core Intel Core i7.

**Comment by chekalsky** [comment]
I've removed GPU drivers and the generator became 5x times slower.
Tried to install apex and used `to_fp16=True` but it didn't have any impact on Tesla T4 performance.

**Comment by minimaxir** [comment]
Found the issue: it's the `repetition_penalty` parameter. Using it w/ a GPU causes a massive performance drop which doesn't happen if the parameter is omitted.

I made no changes there so I'll work on filing an issue to base Transformers.

**Comment by minimaxir** [comment]
Issue filed. Closing since it's not on this end.

**Comment by breadbrowser** [comment]
i use a p100 and i can train a model in 31 minutes
