### ISSUE TITLE
Generation with Multi GPUs?

### ISSUE THREAD

**Issue by PaulBellow** [minimaxir/aitextgen#35]
Anything I need to do to get it to use multiple GPUs for text generation? I remember you added it to gpt-2-simple, and I've seen that AITEXTGEN has it for training, but I was curious about generation. I finally caved and signed up for Google Cloud, and I was curious whether I would see much of a speed increase getting a Jupyter notebook with 2 GPUs. Maybe just a T4 and fp16 is faster than T4x2? Thanks in advance!

**Comment by minimaxir** [comment]
I don't recall adding multi-GPU generation to gpt-2-simple, just for training.

Multi-GPU depends on base-transformers, it's way out of scope for here only.

**Comment by PaulBellow** [comment]
Okay, cool. I wasn't sure if you had for training + generation or just training. 

No worries...
