### ISSUE TITLE
Support for DistilGPT2 model

### ISSUE THREAD

**Issue by vio-codes** [minimaxir/aitextgen#36]
I know that most people are looking for the bigger models, is there a possibility to train distilGPT2 to get lower latency when it comes to inference.
Lower latency would come in handy if you want to build a real-time application.

**Comment by minimaxir** [comment]
DistilGPT2 is supported natively via the downloading-model workflow:

```python
ai = aitextgen(model="distilgpt2")
```

That can be finetuned as normal. However, distilgpt2 is about the same size as the 117M model, and not necessarily better for _generation_.
