### ISSUE TITLE
Not able to run Finetune124M GPT-2 model  on colab 

### ISSUE THREAD

**Issue by suchitraGit** [minimaxir/aitextgen#38]
When run ai.train()  I get below error.

06/30/2020 06:51:36 — INFO — aitextgen.TokenDataset — Encoding 269 sets of tokens from article_mod.txt.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-8-ab07f0ad7ce9> in <module>()
      7          save_gdrive=False,
      8          learning_rate=1e-4,
----> 9          batch_size=1,)

5 frames
/usr/local/lib/python3.6/dist-packages/transformers/tokenization_utils_fast.py in _batch_encode_plus(self, batch_text_or_text_pairs, add_special_tokens, padding_strategy, truncation_strategy, max_length, stride, is_pretokenized, pad_to_multiple_of, return_tensors, return_token_type_ids, return_attention_mask, return_overflowing_tokens, return_special_tokens_mask, return_offsets_mapping, return_length, verbose, **kwargs)
    311 
    312         if kwargs:
--> 313             raise ValueError(f"Keyword arguments {kwargs} not recognized.")
    314 
    315         # Set the truncation and padding strategy and restore the initial configuration

ValueError: Keyword arguments {'return_attention_masks': False} not recognized.

**Comment by minimaxir** [comment]
This was broken in transformers 3.0.0 (#40)

I'll hardcode the version in the Colab notebook for the time being.

**Comment by minimaxir** [comment]
Fixed now in the notebook.
