### ISSUE TITLE
Generating 'complete' text

### ISSUE THREAD

**Issue by HarshaLaxman** [minimaxir/aitextgen#43]
Using a small (10) or large (100) max_length I tend to get chopped off sentences.
ex:
`One in five Americans are overweight, according to a new`

I don't know whether the cause of this is aitextgen or gpt-2 etc. but I thought it was worth asking if there's a way to get complete sentences. My workaround is to chop off anything after the last period/!/? (works better with longer text)

**Comment by minimaxir** [comment]
You'll want to use the `eos_token` parameter to `generate()` which will cause generation to stop once it hits said token, although I haven't explicitly tested it for this use case.

**Comment by HarshaLaxman** [comment]
Thanks :)
