### ISSUE TITLE
torch>=1.3

### ISSUE THREAD

**Issue by 4omp** [minimaxir/aitextgen#47]
Hi! Sorry for so noob question, but when i try to pip3 install aitextgen i have this error:
ERROR: Could not find a version that satisfies the requirement torch>=1.3 (from pytorch-lightning>=0.7.6->aitextgen) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch>=1.3 (from pytorch-lightning>=0.7.6->aitextgen)

I try to google it, but nothing similar was found.

**Comment by minimaxir** [comment]
That is...weird.

Does it work if you `pip3 install torch` directly?

**Comment by 4omp** [comment]
No, i try different type of install, also try to install in clear python, and have this error
![Screenshot_2](https://user-images.githubusercontent.com/11017531/86780385-5f38a880-c065-11ea-88be-ca839d6e41be.png)
