### ISSUE TITLE
Saving genterate_to_file is there a way to write the name of the file

### ISSUE THREAD

**Issue by walter-grace** [minimaxir/aitextgen#51]
I have code that I want to display from the file it saves, how can I rename the generated files to something more simple from the code itself?

**Comment by minimaxir** [comment]
There isn't a way to specify the output file; by design that is done to avoid accidentally overwriting the file.

What are you trying to do that requires a fixed file?

**Comment by walter-grace** [comment]
I am having issues getting the output from ai.generate getting to display on the tkinter gui I have set up. I use the ai.generate_to_files to then just read the file instead out the output from ai. generate(). Id love to be able to either have the text from ai.generate() to display right after it runs or be able to save the file and just display the file.

Here is my code: 
`from tkinter import *
from aitextgen import aitextgen
import Pmw, sys

gui = Tk(className='Text GANS')
e = Entry(gui, width=50)
e.pack()

gui.geometry("740x440")

def labelIt():
    myLabel1 = Label(gui, text="Hold please...")
    myLabel2 = Label(gui, text="Your prompt is.." + e.get()) 
    myLabel1.pack()
    myLabel2.pack()


def callBack():
    hello = print(":)")
    Mylabel3 = Label(gui, text=hello)
    Mylabel3.pack()


    ai = aitextgen()
    ai.generate(n=3, prompt=e.get(), max_length=210, temperature=1.2)
    ai.generate_to_file(n=3, prompt=e.get(), max_length=100, temperature=0.9)
    myLabel = Label(gui, text="Until I can figure out how to input the gen text here go check your console")
    myLabel.pack()


def genText():

    filename = "ATG_20200714_043751_26459826.txt"


    top = Frame(gui); top.pack(side='top')
    text = Pmw.ScrolledText(top,
       borderframe=30, 
       vscrollmode='dynamic', 
       hscrollmode='dynamic',
       labelpos='n', 
       label_text='file %s' % filename,
       text_width=80, 
       text_height=4,
       text_wrap='none',
       )
    text.pack()

    text.insert('end', open(filename,'r').read())
    Button(top, text='Quit', command=gui.destroy).pack(pady=95)


myButton = Button(gui, text="Enter your phrase, then press here", command=callBack)
myButton1 = Button(gui, text="Algo says", command=genText)

mylabel4 = Label(gui, text="It may take a few seconds... after you click")

myButton.pack()
myButton1.pack()
mylabel4.pack()

gui.mainloop()`

**Comment by minimaxir** [comment]
If you are pushing the text to a GUI, wouldn't it make more sense to do a normal `generate()` w/ `return_as_list=True`?

By construction, the most recently-generated file will be first alphabetically, so you can use `os.path` and retrieve it that way.

**Comment by walter-grace** [comment]
Would you mind helping me in what generate() w/ return_as_list=True would look like?

**Comment by MITEL-UNIUD** [comment]
> If you are pushing the text to a GUI, wouldn't it make more sense to do a normal `generate()` w/ `return_as_list=True`?
> 
> If you do need the file, by construction, the most recently-generated file will be first alphabetically, so you can use `os.path` and retrieve it that way.

While this is a possible solution, one alternative could be that the method returns the name of the generated file, so that, when generating more files, you always know which is the last one (and possibly rename it if needed). Thanks for this excellent software, by the way :)
