### ISSUE TITLE
 Could not find a version that satisfies the requirement torch>=1.3

### ISSUE THREAD

**Issue by Crasher124** [minimaxir/aitextgen#53]
What should i do?

**Comment by StoryHack** [comment]
I'm on Windows 10, and I am getting the same Error when doing the pip3 install. HEre's the exact error I'm getting:

ERROR: Could not find a version that satisfies the requirement torch>=1.3 (from pytorch-lightning>=0.7.6->aitextgen) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch>=1.3 (from pytorch-lightning>=0.7.6->aitextgen)

**Comment by StoryHack** [comment]
Okay, so I guess you have to install torch separately. I followed the pip instructions on [https://pytorch.org/get-started/locally/](https://pytorch.org/get-started/locally/) which for me meant I had to type 

`pip install torch===1.6.0 torchvision===0.7.0 -f https://download.pytorch.org/whl/torch_stable.html`

into a cmd or powershell window before running

`pip3 install aitextgen`

would end successfully.

I also had to install the CUDA runtime or whatever to get things to work with my GPU.

**Comment by Crasher124** [comment]
Thanks it worked
