### ISSUE TITLE
ONNX GPT model

### ISSUE THREAD

**Issue by C00reNUT** [minimaxir/aitextgen#74]
Hello, thank you for your work, any plans to implement ONNX support? 
One possible implementation is here https://github.com/rayhern/convert-gpt2-xl-to-onnx

**Comment by minimaxir** [comment]
Yes; this is intended as the primary feature for 0.5.0. It'll require testing so it's not drop-in.

Thanks for pointing out `onnxruntime_tools.transformers.gpt2_helper`, that might be useful!

**Comment by C00reNUT** [comment]
OK, sounds good. Thank you! :)
