### ISSUE TITLE
cannot import name 'add_start_docstrings_to_callable'

### ISSUE THREAD

**Issue by gg5150** [minimaxir/aitextgen#80]
I put the information in to the aitextgen installer on Google Colab and I get the message above. What does this mean, and how do I fix it?

**Comment by minimaxir** [comment]
No idea, that should not be happening in Colab. Did you try again?

Post a more detailed error message.

**Comment by christegho** [comment]
I am getting the same issue with Google Colab - I installed aitextgen via these intructions because of the issue with the version  of the tokenizers:

```
!pip install transformers==2.9.1
!pip install pytorch-lightning==0.7.6

!pip install -q aitextgen==0.2.3
```

Running this command `from aitextgen import aitextgen`, gave me this error:
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-10-38d9bf9f522e> in <module>()
      6     )
      7 
----> 8 from aitextgen import aitextgen
      9 from aitextgen.colab import mount_gdrive, copy_file_from_gdrive

5 frames
/usr/local/lib/python3.6/dist-packages/transformers/modeling_tf_albert.py in <module>()
     22 
     23 from .configuration_albert import AlbertConfig
---> 24 from .file_utils import MULTIPLE_CHOICE_DUMMY_INPUTS, add_start_docstrings, add_start_docstrings_to_callable
     25 from .modeling_tf_bert import ACT2FN, TFBertSelfAttention
     26 from .modeling_tf_utils import TFPreTrainedModel, get_initializer, keras_serializable, shape_list

ImportError: cannot import name 'add_start_docstrings_to_callable'

---------------------------------------------------------------------------
```

**Comment by christegho** [comment]
The import worked after I ran the installation commands, restarted the runtime and ran the import commands without the installation commands

**Comment by minimaxir** [comment]
Yes, the import command were there for an older iteration of the notebook/dependencies. It should be fine now in the current version.
