### ISSUE TITLE
Equivalent to truncate from gpt2-simple

### ISSUE THREAD

**Issue by flesler** [minimaxir/aitextgen#83]
Hi, I've been using gpt2-simple and wondering what became of the `truncate` here?
Is it not supported here and has to be done by the consumer?

Thanks

**Comment by flesler** [comment]
Been looking at the source, is this handled by the `eos_token` provided in the constructor?

**Comment by briansemrau** [comment]
Truncate is the same as doing this:
```py
truncate_str = '\n'
raw_output = 'this is the output returned from the AI'
output = raw_output.split(truncate_str)[0]
```

**Comment by minimaxir** [comment]
`truncate` in gpt-2-simple was a hacky workaround to account for the fact that due to how that worked, you couldn't end the generation early. (and thus waste computation by generating more than you need to)

The generation from transformers/aitextgen is more "correct" in that it will end early.

I think with the current implementation you can pass a `eos_token_id` to tell `generate()` when to stop, although that's not well-documented.

**Comment by flesler** [comment]
That's useful to know (the `eos_token_id`). Though in my case, and I suppose many cases, you have some sort of endoftext, but also an end of "document". If it's a chatbot, the eos_token_id would signal the end of the thread. But when you are generating text, you probably want just one message (so, until the "end of message" instead).

Any way to hack it? swapping the `eos_token_id` in the model in-memory when generating, would it be feasible and a good idea?

**Comment by briansemrau** [comment]
You can set the eos_token_id to whatever you like. From my own implementation:
```py
truncate_char = '\n'
eos = ai.tokenizer._convert_token_to_id(ai.tokenizer._tokenize(truncate_char)[0])
output = ai.generate(..., eos_token_id=eos)
```
This may result in your output including `<|endoftext|>`, but if you pass in `bad_words_ids` you can prevent that output.
For example:
```py
bad_words = ['<|endoftext|>', '\r', 'any bad phrase']
bad_tokens = [[tokenizer._convert_token_to_id(token_id)    # this is done in case we want to block whitespace 
               for token_id in tokenizer._tokenize(word)]  # such as '\n\n' that are removed in normal tokenization
              for word in bad_words]
output = ai.generate(..., bad_words_ids=bad_tokens)
```

**Comment by flesler** [comment]
Beautiful! That's what I needed. I included the "end of document" always before `<|endoftext|>` so it should never happen that I get it. This is awesome, will try it tomorrow!

**Comment by briansemrau** [comment]
eos_token_id and bad_words_ids are both used by the generate function in the huggingface transformers module

**Comment by atulmy** [comment]
@briansemrau, I was using your suggestion to mimic `stop` from GPT-3 i.e. `truncate` to end the generation process, especially for chatbot usage but encountered following issue:
```
eos = ai.tokenizer._convert_token_to_id(ai.tokenizer._tokenize(truncate_char)[0])
AttributeError: 'GPT2TokenizerFast' object has no attribute '_convert_token_to_id'
```

**Comment by briansemrau** [comment]
> 
> 
> @briansemrau, I was using your suggestion to mimic `stop` from GPT-3 i.e. `truncate` to end the generation process, especially for chatbot usage but encountered following issue:
> 
> ```
> eos = ai.tokenizer._convert_token_to_id(ai.tokenizer._tokenize(truncate_char)[0])
> AttributeError: 'GPT2TokenizerFast' object has no attribute '_convert_token_to_id'
> ```

Verify that you're using the correct/up-to-date version of transformers. `_convert_token_to_id` is a function within GPT2TokenizerFast's superclass PreTrainedTokenizer, so I couldn't say what's wrong.

**Comment by atulmy** [comment]
`pip list`
transformers 4.3.3

I think this is the latest version https://pypi.org/project/transformers/

**Comment by atulmy** [comment]
Any idea what might be going wrong with `AttributeError: 'GPT2TokenizerFast' object has no attribute '_convert_token_to_id'` issue? 

@briansemrau @minimaxir

**Comment by minimaxir** [comment]
Are you using `tokenizers` 0.10.2? Possible there's a version mismatch.

**Comment by atulmy** [comment]
`pip list`
tokenizers 0.10.1

Since `requirements.txt` does not point to any fix version of `tokenizers`, which version is appropriate?

**Comment by DhvanilPatel** [comment]
Hi @minimaxir, I'm facing the same problem as @atulmy. 

`AttributeError: 'GPT2TokenizerFast' object has no attribute '_convert_token_to_id'`

I'm using `tokenizers==0.10.1` and `transformers==4.4.0`.

**Comment by atulmy** [comment]
@DhvanilPatel did you find a solution?

**Comment by atulmy** [comment]
Found a solution which seems to work:
```
truncate_char = '###'
eos = ai.tokenizer.convert_tokens_to_ids(ai.tokenizer.tokenize(truncate_char)[0])

# ai.generate()
ai.generate(n=1, prompt=text, max_length=200, temperature=0.7, top_p=1, eos_token_id=eos)
```

requirements.txt:
```
aitextgen==0.4.1
tokenizers==0.10.1
pytorch-lightning==1.2.4
torch==1.8.0
transformers==4.4.2
```

**Comment by atulmy** [comment]
Is there a way to pass multiple `eos_token_id`?

@flesler / @minimaxir?

Example:
```python
truncate_char1 = '###'
truncate_char2 = 'Bot'
eos = ai.tokenizer.convert_tokens_to_id([
  ai.tokenizer.tokenize(truncate_char1)[0],
  ai.tokenizer.tokenize(truncate_char2)[0]
])
```
