### ISSUE TITLE
`generate` limits prompt by number of characters, not number of tokens

### ISSUE THREAD

**Issue by briansemrau** [minimaxir/aitextgen#84]
When using GPT-2 medium, I noticed that the maximum number of characters I could put in my prompt before it throws an assert is 1023. However, I should be limited to 1024 tokens, not 1023 characters. This greatly reduces the allowed prompt size by a factor of 2-4.

**Comment by minimaxir** [comment]
Fixed in 0.4.0, let me know if that works.
