### ISSUE TITLE
Finetuning notebook doesn't work

### ISSUE THREAD

**Issue by gingsi** [minimaxir/aitextgen#87]
Hello,

Your notebook: "Finetune OpenAI's 124M GPT-2 model on your own dataset (GPU)"

https://colab.research.google.com/drive/15qBZx5y9rdaQSyWpsreMDnTiZ5IlN0zD?usp=sharing

gives the following error in the first cell:

VersionConflict: tokenizers==0.9.4 is required for a normal functioning of this module, but found tokenizers==0.10.0.

I have tried installing various versions of the packages tokenizers and transformers but the error is always the above.

Error stack attached: [STACK.txt](https://github.com/minimaxir/aitextgen/files/5888623/STACK.txt)

Interestingly, I don't have this problem on my local machine, the aitextgen import works (windows 10, conda 4.9.2, python 3.8.5, pytorch 1.7.1+cu11, aitextgen 0.3.0)

Best

**Comment by tigeba** [comment]
I think this is a result of some upstream dependencies changing.  I was able to fix this by manually installing the deps, ignoring aitexgens requirements.

`!pip install -q transformers>=4.0.0
!pip install -q fire>=0.3.0
!pip install -q pytorch-lightning>=1.0.8
!pip install -q tokenizers>=1.0.0
!pip install -q torch>=1.6.0
!pip install -q aitextgen --no-deps`

**Comment by minimaxir** [comment]
This will be fixed in 0.4.0 (by not requiring a Tokenizers dependency because they like to specify their own)

**Comment by minimaxir** [comment]
0.4.0 has been released and I verified the Colab Notebook works as is. (and made a few improvements!)
