### ISSUE TITLE
OverflowError: Python int too large to convert to C long

### ISSUE THREAD

**Issue by valentina-bec** [minimaxir/aitextgen#95]
when importing the model: 

 `from aitextgen import aitextgen`

i got the error: 

> csv.field_size_limit(sys.maxsize)
> OverflowError: Python int too large to convert to C long

solved by changing 
`csv.field_size_limit(sys.maxsize)`
in TokenDataset.py

by : 
```
maxInt = sys.maxsize
try:
    csv.field_size_limit(maxInt)
except OverflowError:
    maxInt = int(maxInt/10)
```

Does this change affect the model?

**Comment by MarcusLlewellyn** [comment]
So, I'm out of my depth here. But this looks like it is expecting a C long, but `sys.maxsize` returns the value for a C long long or `9223372036854775807` on my system (Python 3.8.7 64-bit on Windows 10). I think that the maximum value in this case might actually need to be `2^32 - 1` or `2,147,483,647`.

**Comment by minimaxir** [comment]
This was added with #67 

That change will not affect the model/dataset construction at all.

What OS are you using? I see `9223372036854775807` as well. I have no issues explicitly setting `2**32 - 1`.

**Comment by MarcusLlewellyn** [comment]
@minimaxir Windows 10 build 19042 64-bit with Python 3.8.7 64-bit.

**Comment by smt923** [comment]
I have this issue also, Windows 10 20H2 (19042.804), using Python 3.9.2, the change in TokenDataset.py also fixed it for me and allows me to import and generate 

for what it's worth I also see `9223372036854775807`  for `sys.maxsize`

**Comment by minimaxir** [comment]
So this is apparently a [complicated quirk](https://stackoverflow.com/questions/15063936/csv-error-field-larger-than-field-limit-131072). From that, it seems `2 ** 31 - 1` is fine.
