### ISSUE TITLE
Overwriting Base Model Vocabulary

### ISSUE THREAD

**Issue by ashish735** [minimaxir/aitextgen#98]
Hi Max
Really an awesome project created by you,

I have a doubt that when I train the model on my new file, I guess it is overwriting the base model vocabulary, Is there any way to stop it from overwriting the base model vocabulary?

**Comment by minimaxir** [comment]
What do you mean "base model vocabulary"? The tokenizer uses the base GPT-2 tokenizer unless you provide your own.

**Comment by ashish735** [comment]
Hi Max

Thanks for the reply, So is there a way to not overwrite the base GPT-2 tokenizer and just combine my tokenizer with the base GPT-2 tokenizer when I am training on my own dataset?
